/**
 * Expo Config Plugin: SSL Certificate Pinning
 *
 * This plugin configures SSL certificate pinning for Android and iOS builds.
 *
 * Android: Creates network_security_config.xml with certificate pins
 * iOS: Configures App Transport Security and enables pinning
 *
 * Usage in app.config.js:
 *   plugins: [
 *     ['./plugins/withSSLPinning', {
 *       domains: {
 *         'api.flow.gkbj.org': ['sha256/...pin1...', 'sha256/...pin2...'],
 *         'mqtt.flow.gkbj.org': ['sha256/...pin1...', 'sha256/...pin2...'],
 *       },
 *     }],
 *   ],
 */

const {
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Generate Android network_security_config.xml content
 */
function generateNetworkSecurityConfig(domains) {
  const domainConfigs = Object.entries(domains)
    .map(([domain, pins]) => {
      const pinElements = pins
        .map((pin) => `            <pin digest="SHA-256">${pin.replace('sha256/', '')}</pin>`)
        .join('\n');

      return `        <domain-config>
            <domain includeSubdomains="true">${domain}</domain>
            <pin-set expiration="2026-01-01">
${pinElements}
            </pin-set>
        </domain-config>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Network Security Configuration for FaithFlow Mobile App

  This file enforces SSL certificate pinning for specified domains.
  Generated by withSSLPinning config plugin.

  WARNING: Update pins before certificates expire!
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>

    <!-- Debug configuration (development only) -->
    <debug-overrides>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>

    <!-- Domain-specific pinning configurations -->
${domainConfigs}
</network-security-config>
`;
}

/**
 * Add network security config to Android
 */
function withAndroidNetworkSecurity(config, domains) {
  // Step 1: Create the network_security_config.xml file
  config = withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const projectRoot = modConfig.modRequest.projectRoot;
      const resXmlPath = path.join(
        projectRoot,
        'android',
        'app',
        'src',
        'main',
        'res',
        'xml'
      );

      // Create xml directory if it doesn't exist
      if (!fs.existsSync(resXmlPath)) {
        fs.mkdirSync(resXmlPath, { recursive: true });
      }

      // Write network security config
      const configContent = generateNetworkSecurityConfig(domains);
      const configPath = path.join(resXmlPath, 'network_security_config.xml');
      fs.writeFileSync(configPath, configContent);

      console.log('[withSSLPinning] Created network_security_config.xml');
      return modConfig;
    },
  ]);

  // Step 2: Reference the config in AndroidManifest.xml
  config = withAndroidManifest(config, (modConfig) => {
    const mainApplication = modConfig.modResults.manifest.application?.[0];

    if (mainApplication) {
      mainApplication.$['android:networkSecurityConfig'] =
        '@xml/network_security_config';
      console.log('[withSSLPinning] Added networkSecurityConfig to AndroidManifest.xml');
    }

    return modConfig;
  });

  return config;
}

/**
 * Configure iOS App Transport Security
 */
function withiOSAppTransportSecurity(config, domains) {
  return withInfoPlist(config, (modConfig) => {
    // Get or create NSAppTransportSecurity dictionary
    const ats = modConfig.modResults.NSAppTransportSecurity || {};

    // Require certificate transparency
    ats.NSRequiresCertificateTransparency = true;

    // Configure pinned domains
    const pinnedDomains = {};
    for (const domain of Object.keys(domains)) {
      pinnedDomains[domain] = {
        // Require TLS 1.2+
        NSExceptionMinimumTLSVersion: 'TLSv1.2',
        // Require forward secrecy
        NSExceptionRequiresForwardSecrecy: true,
        // Include subdomains
        NSIncludesSubdomains: true,
        // Require valid certificate
        NSThirdPartyExceptionAllowsInsecureHTTPLoads: false,
      };
    }

    // Set exception domains (production domains with security requirements)
    ats.NSExceptionDomains = {
      ...ats.NSExceptionDomains,
      ...pinnedDomains,
    };

    modConfig.modResults.NSAppTransportSecurity = ats;

    console.log('[withSSLPinning] Configured iOS App Transport Security');
    return modConfig;
  });
}

/**
 * Main plugin function
 */
function withSSLPinning(config, options = {}) {
  const { domains = {} } = options;

  // Skip if no domains configured
  if (Object.keys(domains).length === 0) {
    console.warn('[withSSLPinning] No domains configured, skipping SSL pinning setup');
    return config;
  }

  console.log(`[withSSLPinning] Configuring SSL pinning for ${Object.keys(domains).length} domains`);

  // Apply Android configuration
  config = withAndroidNetworkSecurity(config, domains);

  // Apply iOS configuration
  config = withiOSAppTransportSecurity(config, domains);

  return config;
}

module.exports = withSSLPinning;
