"""
Standardized error codes for accounting module.
All error codes are designed to be i18n-friendly.
"""

# Journal Errors
JOURNAL_NOT_BALANCED = "JOURNAL_NOT_BALANCED"
CANNOT_EDIT_APPROVED_JOURNAL = "CANNOT_EDIT_APPROVED_JOURNAL"
DUPLICATE_JOURNAL_LINES = "DUPLICATE_JOURNAL_LINES"
INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"

# COA Errors
ACCOUNT_CODE_EXISTS = "ACCOUNT_CODE_EXISTS"
CANNOT_DELETE_USED_ACCOUNT = "CANNOT_DELETE_USED_ACCOUNT"
COA_EDIT_NOT_ALLOWED = "COA_EDIT_NOT_ALLOWED"

# Beginning Balance Errors
BEGINNING_BALANCE_NOT_BALANCED = "BEGINNING_BALANCE_NOT_BALANCED"

# Budget Errors
BUDGET_MONTHLY_ANNUAL_MISMATCH = "BUDGET_MONTHLY_ANNUAL_MISMATCH"

# Fiscal Period Errors
PERIOD_LOCKED = "PERIOD_LOCKED"
PERIOD_CLOSED = "PERIOD_CLOSED"
INVALID_PERIOD_OPERATION = "INVALID_PERIOD_OPERATION"

# Year-End Errors
YEAR_ALREADY_CLOSED = "YEAR_ALREADY_CLOSED"
CLOSING_FAILED = "CLOSING_FAILED"

# Validation Errors
INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
INVALID_FISCAL_YEAR = "INVALID_FISCAL_YEAR"
VALIDATION_ERROR = "VALIDATION_ERROR"

# File Upload Errors
FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
INVALID_FILE_TYPE = "INVALID_FILE_TYPE"

# Multi-Tenant Errors
CHURCH_ACCESS_DENIED = "CHURCH_ACCESS_DENIED"

# Database Errors
TRANSACTION_FAILED = "TRANSACTION_FAILED"

# Pagination Errors
PAGINATION_REQUIRED = "PAGINATION_REQUIRED"
